### ISSUE TITLE
Linux mint "make" is giving me errors

### ISSUE THREAD

**Issue by t0nitogp** [fsphil/hacktv#114] opened 2024-07-03 12:16 UTC
I'm trying to build hackTV and I ran into an issue, I installed the requirements 

apt-get install libhackrf-dev libavutil-dev libavdevice-dev libswresample-dev libswscale-dev libavformat-dev libavcodec-dev

When I go to "make" command it starts running and stops at:

/usr/bin/ld: rf_hack.o: in function 'rf_hackrf_open':
/home/mint/hacktv/src/rf_hackrf.c:365: undefined reference to 'hackrf_get_transfer_buffer_size'
/usr/bin/ld: /home/mint/hacktv/src/rf_hackrf.c:367: undefined reference to 'hackrf_get_transfer_buffer_size'
collect2: error: ld returned 1 exit status
make: *** [Makefile:36: hacktv] Error 1

**Comment by t0nitogp** [comment] 2024-07-03 12:35
![IMG_20240703_133029](https://github.com/fsphil/hacktv/assets/161924389/b69a661d-5d88-4808-a95f-dfca1f9aab0f)

**Comment by fsphil** [comment] 2024-07-03 20:05
This is a duplicate of #106

Basically your system is still using a very old version of libhackrf that lacks the `hackrf_get_transfer_buffer_size()` function.
You can simply replace that function call with `262144`.

**Comment by t0nitogp** [comment] 2024-07-03 21:08
You mean edit the rf_hackrf.c and replace on both lines 'hackrf_get_transfer_buffer_size()' with 262144?

I'm sorry if this is a stupid question but I'm very new to Linux, I'm using the latest version of Mint, is there a way to maybe update a newer version of libhackrf and try again?

**Comment by t0nitogp** [comment] 2024-07-04 06:46
> This is a duplicate of #106
> 
> Basically your system is still using a very old version of libhackrf that lacks the `hackrf_get_transfer_buffer_size()` function. You can simply replace that function call with `262144`.
> 
> I might just remove this call until Ubuntu and Mint fix their packages.

I tried replacing `hackrf_get_transfer_buffer_size()` with 262144 and just got more errors. I know nothing about code...

**Comment by fsphil** [comment] 2024-07-04 09:13
I've pushed a change that removes that function call, that should compile for you.

**Comment by t0nitogp** [comment] 2024-07-04 09:42
Thank you!

**Comment by fsphil** [comment] 2024-07-04 10:49
Did it work?

**Comment by t0nitogp** [comment] 2024-07-04 11:50
I didn't have a chance to it try yet, but as soon as I do I'll let you know :)

**Comment by fsphil** [comment] 2024-07-04 17:19
Thanks for reporting back!

**Closed by fsphil** 2024-07-04 17:19 UTC
